# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.7847, 0.8932, 0.3705, 0.1744, 0.2625, 0.7690, 0.1820],
        [0.5546, 0.1921, 0.6482, 0.0823, 0.4131, 0.6468, 0.0771],
        [0.0585, 0.3785, 0.6862, 0.9024, 0.1643, 0.0989, 0.7447],
        [0.7416, 0.4512, 0.8655, 0.5881, 0.9279, 0.1186, 0.1729],
        [0.1747, 0.6671, 0.9314, 0.7676, 0.1022, 0.4728, 0.5529],
        [0.3634, 0.1843, 0.6872, 0.2749, 0.0278, 0.3686, 0.8248],
        [0.7286, 0.6397, 0.6610, 0.3405, 0.4610, 0.5301, 0.4615]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
y = torch.rand( 1, 7)
# Perform matrix multiplication 
matrix_mult = torch.matmul(x , y.T)
matrix_mult

tensor([[1.7381],
        [1.3521],
        [2.2682],
        [2.4840],
        [2.4379],
        [1.6769],
        [2.2170]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED = 0


# Create two random tensors
torch.manual_seed = RANDOM_SEED
random_tensor_x = torch.rand( 7, 7)
torch.manual_seed = RANDOM_SEED
random_tensor_y = torch.rand(1, 7)

# Matrix multiply tensors
random_matrix_mul = torch.matmul(random_tensor_x, random_tensor_y.T)
random_matrix_mul


tensor([[1.9769],
        [2.3053],
        [1.9960],
        [2.5410],
        [2.3491],
        [1.6416],
        [2.4276]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU

tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B



Device: cuda


(tensor([[0.4284, 0.0643, 0.0374],
         [0.1362, 0.1236, 0.9632]], device='cuda:0'),
 tensor([[0.4137, 0.6340, 0.9264],
         [0.8741, 0.1221, 0.4600]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
matrix_mul = torch.matmul(tensor_A, tensor_B.T)
matrix_mul, matrix_mul.shape

(tensor([[0.2526, 0.3995],
         [1.0271, 0.5773]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
max = torch.max(matrix_mul)
# Find min
min = torch.min(matrix_mul)

max, min


(tensor(1.0271, device='cuda:0'), tensor(0.2526, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
# Find arg max
arg_max = torch.argmax(matrix_mul)

# Find arg min
arg_min = torch.argmin(matrix_mul)

arg_min, arg_max

(tensor(0, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))


# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)


tensor([[[[0.0167, 0.9878, 0.1163, 0.8241, 0.2958, 0.5862, 0.5102, 0.3372,
           0.0523, 0.2529]]]]) torch.Size([1, 1, 1, 10])
tensor([0.0167, 0.9878, 0.1163, 0.8241, 0.2958, 0.5862, 0.5102, 0.3372, 0.0523,
        0.2529]) torch.Size([10])
